export const testListElement = {
  id: 'testId',
  refPortion: 10,
  userAmount: 5,
  name: 'testName',
  fat: 35,
  carb: 10,
  fibre: 15,
  protein: 25,
  saturatedFat: 11,
  sugar: 8,
  salt: 9,
  calories: 2019,
}

export const testEmptyListElement = {
  id: 'testId',
  refPortion: 0,
  userAmount: 0,
  name: 'testName',
  fat: 0,
  carb: 0,
  fibre: 0,
  protein: 0,
  saturatedFat: 0,
  sugar: 0,
  salt: 0,
  calories: 0,
}


export const testList = [
  {
    id: 'testId1',
    refPortion: 10,
    userAmount: 5,
    name: 'testName1',
    fat: 10,
    carb: 5,
    fibre: 9,
    protein: 1,
    saturatedFat: 2,
    sugar: 3,
    salt: 4,
    calories: 1000,
  },
  {
    id: 'testId2',
    refPortion: 10,
    userAmount: 5,
    name: 'testName2',
    fat: 20,
    carb: 7,
    fibre: 100,
    protein: 5,
    saturatedFat: 6,
    sugar: 7,
    salt: 8,
    calories: 2000,
  },
  {
    id: 'testId3',
    refPortion: 2,
    userAmount: 1,
    name: 'testName3',
    fat: 253,
    carb: 12,
    fibre: 53,
    protein: 8,
    saturatedFat: 9,
    sugar: 10,
    salt: 11,
    calories: 2011,
  },
]
